// src/utils/sponsorships.js
//
// COHORT SPONSORSHIP
//
// A company funds one TEAM (not a whole cohort, one team is a far easier
// first sale, and a cohort can then carry several sponsors, or run with some
// teams sponsored and some not). The money pays member stipends.
//
// THE LINE THAT KEEPS THIS LEGAL
// A sponsor may WATCH, ACKNOWLEDGE and RECRUIT.
// A sponsor may never DIRECT, REVIEW or OWN.
//
// If a sponsor specifies requirements, reviews deliverables, or takes the IP,
// the substance becomes "company bought labour, platform was the middleman", // the stipend starts to look like a wage and we become a staffing
// intermediary. Briefs are generated by She Model Tech; the TEAM owns its
// code; the sponsor funds the programme and is acknowledged for it.
//
// Sponsors therefore get NO workspace access, no team seat, and no approval
// rights. What they get is defined in SPONSOR_ENTITLEMENTS below.
//
// Stipends are a TRAINING STIPEND for participating, not payment for
// delivery. Distribution reuses the existing paymentConfirmations flow
// (amount owed → marked paid → member confirms received → dispute room),
// which is already built and hardened in firestore.rules.
//
// NOTE: payment collection and payout are NOT built yet, this module models
// the structure so cohorts, tagging and reporting all work now. Sponsorship
// is invoiced manually until billing ships.

import {
  collection,
  doc,
  addDoc,
  getDoc,
  getDocs,
  updateDoc,
  query,
  where,
  serverTimestamp,
} from 'firebase/firestore';
import { db } from '../firebase/config';

export const SPONSORSHIP_STATUS = {
  PLEDGED: 'pledged', // agreed, not yet paid
  FUNDED: 'funded', // money received, REQUIRED before the cohort starts
  DISTRIBUTED: 'distributed', // stipends paid out to members
  CANCELLED: 'cancelled',
};

// How a team is funded. Shown as a tag on the project, with the sponsor logo.
export const FUNDING_TYPE = {
  COMMUNITY: 'community', // unsponsored, the default, still fully free
  SPONSORED: 'sponsored', // a company funded stipends for this team
};

// Share retained for programme costs and overhead. Passing through 100% means
// the organisation runs on the founder's own money, which is how this fails.
// ~20-25% is standard and defensible to funders.
export const OVERHEAD_RATE = 0.22;

export const SPONSOR_ENTITLEMENTS = [
  'Read-only progress updates on the team you funded',
  'Your name and logo on the project and the cohort page',
  'Acknowledgement in the weekly community email',
  'An impact report when the cohort completes',
  'A two-week first look at the graduates you funded',
  'An invitation to the cohort demo day',
];

// Stated explicitly, because sponsors drift toward involvement once they've
// paid. Set this expectation at the point of sale, in writing.
export const SPONSOR_LIMITS = [
  'No access to the project workspace',
  'No seat on the team',
  'No specifying requirements or reviewing deliverables',
  'The team owns its code and its decisions',
];

/** Split a sponsorship into stipends and overhead. */
export const computeStipends = (amount, memberCount) => {
  const total = Number(amount) || 0;
  const overhead = Math.round(total * OVERHEAD_RATE);
  const pool = total - overhead;
  const perMember = memberCount > 0 ? Math.floor(pool / memberCount) : 0;
  return {
    total,
    overhead,
    stipendPool: pool,
    perMember,
    // Rounding remainder stays with the organisation.
    remainder: pool - perMember * memberCount,
  };
};

/**
 * Record a sponsorship. Created as PLEDGED; must reach FUNDED before the
 * cohort starts, otherwise we float stipends out of our own pocket for
 * eight weeks, which we cannot do.
 */
export const createSponsorship = async ({
  cohortId,
  projectId,
  company,
  amount,
  contactName,
  contactEmail,
  notes,
}) => {
  const ref = await addDoc(collection(db, 'sponsorships'), {
    cohortId,
    projectId: projectId || null, // null = not yet allocated to a team
    companyId: company.id || null,
    companyName: company.name,
    companyLogo: company.logoUrl || null,
    companyWebsite: company.website || null,
    amount: Number(amount) || 0,
    currency: 'USD',
    status: SPONSORSHIP_STATUS.PLEDGED,
    contactName: contactName || null,
    contactEmail: contactEmail || null,
    notes: notes || null,
    // First-look window opens when the cohort completes.
    firstLookDays: 14,
    createdAt: serverTimestamp(),
  });
  return ref.id;
};

/** Mark funds received, and tag the team so the badge shows on the project. */
export const markFunded = async (sponsorshipId) => {
  const snap = await getDoc(doc(db, 'sponsorships', sponsorshipId));
  if (!snap.exists()) throw new Error('Sponsorship not found.');
  const s = snap.data();

  await updateDoc(doc(db, 'sponsorships', sponsorshipId), {
    status: SPONSORSHIP_STATUS.FUNDED,
    fundedAt: serverTimestamp(),
  });

  if (s.projectId) await tagProjectAsSponsored(s.projectId, s, sponsorshipId);
};

/**
 * Put the sponsor's name and logo on the team's project.
 * This is the acknowledgement they're paying for, and it must be visible to
 * members, they should know who funded their stipend.
 */
export const tagProjectAsSponsored = async (projectId, sponsorship, sponsorshipId) =>
  updateDoc(doc(db, 'projects', projectId), {
    fundingType: FUNDING_TYPE.SPONSORED,
    sponsorshipId,
    sponsorName: sponsorship.companyName,
    sponsorLogo: sponsorship.companyLogo || null,
    sponsorWebsite: sponsorship.companyWebsite || null,
    updatedAt: serverTimestamp(),
  });

/** Allocate a pledged sponsorship to a specific team. */
export const allocateToProject = async (sponsorshipId, projectId) => {
  const snap = await getDoc(doc(db, 'sponsorships', sponsorshipId));
  if (!snap.exists()) throw new Error('Sponsorship not found.');
  const s = snap.data();
  await updateDoc(doc(db, 'sponsorships', sponsorshipId), {
    projectId,
    updatedAt: serverTimestamp(),
  });
  if (s.status === SPONSORSHIP_STATUS.FUNDED) {
    await tagProjectAsSponsored(projectId, s, sponsorshipId);
  }
};

export const getSponsorshipsForCohort = async (cohortId) => {
  const snap = await getDocs(
    query(collection(db, 'sponsorships'), where('cohortId', '==', cohortId))
  );
  return snap.docs.map((d) => ({ id: d.id, ...d.data() }));
};

export const getSponsorshipsForCompany = async (companyId) => {
  const snap = await getDocs(
    query(collection(db, 'sponsorships'), where('companyId', '==', companyId))
  );
  return snap.docs.map((d) => ({ id: d.id, ...d.data() }));
};

/**
 * Read-only progress summary for the sponsor dashboard.
 * Deliberately coarse: status, milestones and headcount, NOT the workspace,
 * not the forum, not the code in progress. Sponsors watch; they don't review.
 */
export const getSponsorProgress = async (sponsorshipId) => {
  const sSnap = await getDoc(doc(db, 'sponsorships', sponsorshipId));
  if (!sSnap.exists()) return null;
  const s = sSnap.data();
  if (!s.projectId) return { sponsorship: s, project: null };

  const pSnap = await getDoc(doc(db, 'projects', s.projectId));
  if (!pSnap.exists()) return { sponsorship: s, project: null };
  const p = pSnap.data();

  return {
    sponsorship: s,
    project: {
      id: s.projectId,
      title: p.projectTitle || p.title,
      track: p.industryTrack,
      status: p.status,
      reviewStatus: p.reviewStatus,
      startDate: p.startDate,
      endDate: p.endDate,
      teamSize: 1 + (p.members?.length || 0),
      leadName: p.submitterName || null,
      // Only revealed once the work is approved, nothing half-finished.
      repoUrl: p.reviewStatus === 'approved' ? p.reviewRepoUrl : null,
      completedAt: p.completedAt || null,
    },
  };
};

/**
 * Is a sponsor inside their two-week first-look window on the team they
 * funded? First look, never exclusivity, graduates are always discoverable
 * to everyone, and this only affects timing of outreach.
 */
export const isInFirstLookWindow = (sponsorship, cohort) => {
  if (!cohort?.endDate) return false;
  const end = new Date(cohort.endDate);
  const close = new Date(end.getTime() + (sponsorship.firstLookDays || 14) * 86400000);
  const now = new Date();
  return now >= end && now <= close;
};

/** The renewal document: what their money produced. */
export const buildImpactReport = async (sponsorshipId) => {
  const progress = await getSponsorProgress(sponsorshipId);
  if (!progress?.project) return null;
  const { sponsorship, project } = progress;

  const badgeSnap = await getDocs(
    query(collection(db, 'member_badges'), where('projectId', '==', project.id))
  );
  const badges = badgeSnap.docs.map((d) => d.data());
  const split = computeStipends(sponsorship.amount, project.teamSize);

  return {
    sponsor: sponsorship.companyName,
    project: project.title,
    track: project.track,
    womenSupported: project.teamSize,
    completed: ['completed', 'awaiting_payment_confirmation'].includes(project.status),
    badgesEarned: badges.length,
    badgeBreakdown: badges.reduce((acc, b) => {
      acc[b.badgeCategory] = (acc[b.badgeCategory] || 0) + 1;
      return acc;
    }, {}),
    stipendPerMember: split.perMember,
    totalToMembers: split.stipendPool,
    repoUrl: project.repoUrl,
    period: `${project.startDate} to ${project.endDate}`,
  };
};
